-- define the structure of that window
-- structure is defined by buf
-- expose a render/redraw/update function that only accept fixed parameters
-- a close function to close the window
--
-- event handlers?
-- implemented by buffer only keybindings

-- functions
-- refresh (R)
-- fetch (F)
-- export (E)
-- help (?)
